### PR TITLE
Section3 3 circle fade-in

### PR DESCRIPTION
**Pull request by yutzuhsuan**
Hi 帥哥, 圈圈有 face-in 囉

### CODE REVIEW

**Comment by yutzuhsuan** [comment]
LGTM

**Comment by yutzuhsuan** [comment]
很讚喔

**Comment by geniusgordon** [comment]
LGTM

**Comment by yutzuhsuan** [comment]
只寫 css 很讚喔

**Comment by afq984** [comment]
未看先 LGTM

**Comment by chengscott** [comment]
Look good to "us" XD

**Comment by chengscott** [comment]
eslint 1 error is fixed in PR #4 
image

**Pull request merged**
